name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build-artifacts.yml
  publish:
    runs-on: self-hosted
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{needs.build.outputs.artifact}}
      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ${{needs.build.outputs.artifact}}.zip
      - name: Upload artifact to artifact repository
        run: curl --fail -u "${{ secrets.PRIVATE_NEXUS_USERNAME }}":"${{ secrets.PRIVATE_NEXUS_PASSWORD }}" --upload-file ${{needs.build.outputs.artifact}}.zip https:/artifacts.tiobe.com/repository/plugins/tics-intellij-plugin/${{needs.build.outputs.version}}/${{needs.build.outputs.artifact}}.zip
      - name: Trigger Jenkins job
        run: curl -u ${{secrets.JENKINS_API_TOKEN}} ${{secrets.JENKINS_URL}}/job/Intellij-Publish/build?token=intellij-publish
